### ISSUE TITLE
Query support

### ISSUE THREAD

**Issue by Symbolk** [serenadeai/java-tree-sitter#7]
Thanks for the project! I am wondering if this java binding supports tree query like https://github.com/tree-sitter/py-tree-sitter too?Since I want to filter all identifiers with the query s-expression.

**Comment by tmacwill** [comment]
Thanks for reaching out! This project doesn't yet support S-expressions, but would certainly be open to a PR that adds support. We don't have a timeline on our end yet for when we'd be able to support it, though.

**Comment by Symbolk** [comment]
> Thanks for reaching out! This project doesn't yet support S-expressions, but would certainly be open to a PR that adds support. We don't have a timeline on our end yet for when we'd be able to support it, though.

Thanks!
